trainer:
  max_epochs: 50
  max_steps: -1
  accelerator: gpu
  devices: 1
  accumulate_grad_batches: 1
  log_dir: ckpt/mel2mag_44k1
  run_name: mel2mag_hf
  ckpt_every_n_steps: 5000
  val_check_interval: 1000

data:
  raw_wavfile_path: ./data/train/audio
  train_data_dir: ./data/train/train.txt
  val_data_dir: ./data/train/val.txt
  f0_root: ./data/f0
  batch_size: 10
  num_workers: 12
  sampling_rate: 44100
  n_fft: 2048
  hop_size: 512
  win_size: 2048
  fmin: 0.0
  fmax: 22050.0
  num_mels: 128
  num_frames: 128
  compute_mel_in_dataset: true

model:
  # output bins: (n_fft//2+1) - drop_last_freq
  drop_last_freq: true

  # network
  hidden: 256
  n_blocks: 6
  kernel_size: 5
  dropout: 0.0
  f0_max: 1100.0

  # optim
  lr: 2.0e-4
  beta1: 0.8
  beta2: 0.99
  opt_type: AdamW

  # loss
  hf_fmin_hz: 6000.0
  hf_fmax_hz: 15000.0
  hf_weight: 1.0
  hf_gate_ratio: 0.01
  edge_weight: 0.0
  eps: 1.0e-6
